# .github/workflows/deploy.yml
name: 🚀 Scalar CI/CD

on:
  push:
    branches: [ main ] # Dispara automaticamente ao commitar na branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Traz todo o histórico de tags e datas para o gerador do Hugo

      - name: 🛠️ Setup Hugo Environment
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.161.0'
          extended: true # Mantém suporte nativo para SASS/SCSS se seu CSS precisar

      - name: 💾 Active Hugo Cache
        uses: actions/cache@v4
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugo-${{ hashFiles('**/hugo.toml') }}
          restore-keys: |
            ${{ runner.os }}-hugo-

      - name: ⚡ Build with Precision
        # O GitHub Actions roda em ambiente limpo, logo a pasta public não existe previamente.
        # Executamos apenas a Garbage Collection e a Minificação explícita.
        run: hugo --gc --minify

      - name: ☁️ Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # Comando direto apontando para a pasta pública gerada na etapa anterior
          command: pages deploy public --project-name=scalar3